<h1><img alt="jeu de careme" src="<?php echo $urlBase; ?>files/images-max/jeucareme.gif" title="careme" alt="Image careme"></h1>



<br>
<p><i>A l’occasion du Carême, des enfants de sixième ont relu les évangiles de Carême (année C).<br>A partir de ceux-ci, ils ont élaboré une liste de questions. Ils ont ensuite joué au jeu de l'oie avec le plateau proposé.</i></p>
<br>
<h2 class="txt-bleuFonce souligne">LES EVANGILES CHOISIS: ANNEE C:</h2>
<br>

<p>-->Mercredi des cendres: Matthieu 6,1-6.16-18<br>-->Premier dimanche de Carême: Luc 4,1-13<br>-->Second dimanche de Carême: Luc 9,28b-36<br>-->Troisième dimanche de Carême: Luc 13, 1-9<br>-->Quatrième dimanche de Carême: Luc 15, 1-3.11-32<br>-->Cinquième dimanche de carême:Jean 8, 1-11<br>-->Sixième dimanche de Carême: Luc 19, 28-40<br>-->Questions sur la semaine sainte: la Cène, le lavement des pieds, le jardin des oliviers, le vendredi saint, la Résurrection.</p>
<p>Les questions choisies vont être tirées de ces lectures (Sauf questions générales sur le carême). Il faut donc avoir lu les textes au moins une fois et avoir étudié le carême. Voir ci-dessous, les évangiles de Carême, année C.</p>
<br>
<p class="centre"><a href="<?php echo $urlBase; ?>files/other/pdf/evangilescareme.pdf" target="min"><img src="<?php echo $urlBase; ?>files/images-min/pdf.gif"></a></p>





<br>
<h2 class="txt-bleuFonce souligne">LE PLATEAU DE JEU:</h2>
<br>
<p class="centre"><a href="<?php echo $urlBase; ?>files/images-max/jeu3.gif" target="min"><img src="<?php echo $urlBase; ?>files/images-min/jeu3.gif" title="careme" alt="Image careme"></a></p>





<br>
<h2 class="txt-bleuFonce souligne">LES QUESTIONS CHOISIES:</h2>
<br>
<p><i>Devant chaque question, un numéro. <br>Exemple: 1234 signifie que la question peut être posée lorsqu'on tombe sur la case 1, ou la case 2, ou la case 3, ou la case 4. </i></p>
<br>
<p><u>Mercredi des cendres: Questions sur le carême et sur le texte de Matthieu 6.</u><br>*1 2 3 4: Quel jour commence le carême?<br>*1 2 3 4: Que reçoit-on sur le front ou dans les mains le jour du mercredi des cendres?<br>*1 2 3 4: D'où vient la cendre qu'on utilise le mercredi des cendres?<br>*1 2 3 4: Recevoir de la cendre, c'est: (Choisis une des 3 propositions)<br>-->Se reconnaître pécheur et avoir envie de changer de vie?<br>-->Recevoir un sacrement?<br>-->Devenir chrétien?<br>*1 2 3 4: Qu'est-ce que le jeûne?<br>*1 2 3 4: Qu'est-ce que l'aumône? <br>*1 2 3 4: Pendant le carême, on nous demande de prier davantage. Connais-tu le nom de deux prières chrétiennes?<br>*1 2 3 4:
Pour vivre comme des justes devant qui faut-il éviter d'agir pour se faire remarquer?<br>*1 2 3 4 Jésus est sur la montagne. Comment appelle-t-on ceux qui le suivent? <br>*1 2 3 4 Complète la phrase: ''Quand tu fais............... que ta main gauche ignore ce que donne ta main droite.''<br>*1 2 3 4 Lorsque l'on prie, Jésus nous conseille de nous retirer dans une pièce. Qu'elle est cette pièce?<br>*1 2 3 4 Quand je fais l'aumône, dois-je le dire autour de moi? (OUI-NON)<br>*1 2 3 4 Quel verbe signifie "se priver de nourriture"<br>*1 2 3 4 Que dois-tu faire quand tu jeûnes? (donne une réponse au moins)<br>*1 2 3 4 Complète la phrase: "Ton .......... est là, invisible; il voit ce qui est invisible: il te le ............"<br>*1 2 3 4 Complète la phrase: "Ton Père voit ce que tu fais en .........: il te le revaudra."</p>
<br>
<p><u>Tentations: </u><br>*5 6 7 8 9 10 11: Par qui Jésus a-t-il été baptisé?<br>*5 6 7 8 9 10 11: Dans quel fleuve, Jésus a-t-il été baptisé?<br>*5 6 7 8 9 10 11: Jésus ne part pas seul au désert. Qui l'accompagne? <br>*5 6 7 8 9 10 11: Un oiseau est symbole de l'Esprit saint. Quel est cet oiseau? <br>*5 6 7 8 9 10 11: Les chrétiens croient en un Dieu Trinité. Quelles sont les trois personnes de cette Trinité?<br>*5 6 7 8 9 10 11: Dans le texte des tentations, que se passe-t-il au désert?<br>*5 6 7 8 9 10 11: Quel est le temps symbolique que Jésus passe au désert? <br>*5 6 7 8 9 10 11: Par qui Jésus est-il tenté?<br>*5 6 7 8 9 10 11: Une tentation de Jésus: Transformer la pierre en ...........<br>*5 6 7 8 9 10 11: D'un seul regard, Jésus voit tous les royaumes de la terre. Le démon lui dit: "Si tu te ........... devant moi, tu auras tout cela!" <br>*5 6 7 8 9 10 11:Que signifie le mot prosterner?<br>*5 6 7 8 9 10 11: Devant qui seulement peut-on se prosterner?<br>*5 6 7 8 9 10 11: A Jérusalem, il y a une construction et l'on vient de loin pour y offrir des sacrifices à Dieu. Quelle est cette construction?<br>*5 6 7 8 9 10 11: Le démon dit à Jésus qu'il peut se jeter sans crainte du haut du Temple et que des aides viendront le garder, le porter. Qui sont ces aides?<br>*5 6 7 8 9 10 11: Complète la phrase: "Tu ne mettras pas à l'............. le Seigneur ton Dieu."<br>*5 6 7 8 9 10 11: Réponds en choisissant une des trois propositions:<br>-->Jésus est né à Jérusalem<br>-->Jésus a vécu son enfance à Jérusalem<br>-->Jésus est mort à Jérusalem.</p>
<br>
<p><u>Transfiguration: </u><br>*12 13 14 15 16 17 18: Dans le texte de la transfiguration, quels sont les trois disciples qui sont avec Jésus? (Donne au moins un nom)<br>*12 13 14 15 16 17 18: Où vont Jésus et ses disciples?<br>*12 13 14 15 16 17 18: Pourquoi Jésus va-t-il sur la montagne?<br>*12 13 14 15 16 17 18: Pendant que Jésus prie, comment son visage apparaît-il? <br>*12 13 14 15 16 17 18: Pendant que Jésus prie, comment apparaissent ses vêtements?<br>*12 13 14 15 16 17 18: Quels sont les noms des deux hommes qui s'entretiennent avec Jésus?<br>*12 13 14 15 16 17 18: Pierre et ses amis sont-ils en forme ou plutôt endormis? <br>*12 13 14 15 16 17 18: Complète la phrase: "Pierre et ses amis se réveillant virent la ........ de Jésus!"<br>*12 13 14 15 16 17 18: Pierre est heureux d'être là. Il propose à Jésus de dresser des tentes... Combien de tentes? <br>*12 13 14 15 16 17 18: Pour qui Pierre propose-t-il trois tentes? <br>*12 13 14 15 16 17 18: Raconte ce que tu sais sur Moïse. <br>*12 13 14 15 16 17 18: Elle survient et couvre les disciples de son ombre. Qui est-ce? <br>*12 13 14 15 16 17 18: Qu'est-ce qu'une nuée? <br>*12 13 14 15 16 17 18: Complète la phrase: "De la nuée, une ........... se fit entendre." <br>*12 13 14 15 16 17 18:  Complète la phrase: "Celui-ci est mon ..........., celui que j'ai choisi,  ............-le!"</p>
<br>
<p><u>Figuier stérile: </u><br>*19 20 21 22 23 24 25: Comment appelle-t-on les petites histoires que Jésus raconte et qui disent des choses importantes sur Dieu?<br>*19 20 21 22 23 24 25: Qu'est-ce qu'un figuier? <br>*19 20 21 22 23 24 25: Comment s'appelle les fruits du figuier?<br>*19 20 21 22 23 24 25: Dans cette parabole, où est planté le figuier?<br>*19 20 21 22 23 24 25: Un homme vient. Que cherche-t-il sur le figuier? <br>*19 20 21 22 23 24 25:Depuis combien d'années l'homme vient-il chercher du fruit sur le figuier?<br>*19 20 21 22 23 24 25: L'homme ne trouve pas de fruit. Que veut-il faire de l'arbre?<br>*19 20 21 22 23 24 25: Complète la phrase: "A quoi bon le laisser ............... le sol?"<br>*19 20 21 22 23 24 25:  Le vigneron est-il d'accord pour couper l'arbre?<br>*19 20 21 22 23 24 25: Le vigneron demande: "Laisse-le encore .......... année."<br>*19 20 21 22 23 24 25: Que va faire le vigneron pour que l'arbre donne du fruit à l'avenir?<br>*19 20 21 22 23 24 25: Si nous sommes le figuier et que Dieu est le vigneron, que nous dit cette parabole?<br>*19 20 21 22 23 24 25: Connais-tu le titre d'une autre parabole que l'on peut trouver dans l'évangile?<br>*19 20 21 22 23 24 25: C'est l'évangéliste Luc qui nous raconte cette histoire. Donne le nom d'au moins un autre évangéliste?</p>
<br>
<p><u>Fils prodigue: </u><br>*26 27 28 29 30 31 32: Dans la parabole, combien de fils à le père? <br>*26 27 28 29 30 31 32: Que veut le plus jeune fils?<br>*26 27 28 29 30 31 32: Que fait le père?<br>*26 27 28 29 30 31 32: Vers où part le plus jeune fils?<br>*26 27 28 29 30 31 32: Loin de son père, comment vit le jeune fils?<br>*26 27 28 29 30 31 32: Complète la phrase: "Quand il eut tout dépensé une grande famine survint et le fils se trouva dans la ......."<br>*26 27 28 29 30 31 32 Quand il n'a plus rien quel métier fait le fils? <br>*26 27 28 29 30 31 32: Avec son nouveau métier, le fils mange-t-il à sa faim?<br>*26 27 28 29 30 31 32: Le fils est malheureux. Il réfléchit. Vers qui va-t-il retourner? <br>*26 27 28 29 30 31 32 Que va dire le fils au père? Complète la phrase: "Père, j'ai ............. contre le ciel et contre toi. Je ne ........... plus d'être appelé ton fils." <br>*26 27 28 29 30 31 32: Le fils va retourner chez son père et va lui demander de le prendre comme:<br>-->Ouvrier.<br>-->S'il ne s'était rien passé et donc de l'accueillir comme son fils.<br>*26 27 28 29 30 31 32 Quand il voit son fils que fait le père?<br>*26 27 28 29 30 31 32: Que dit le fils (complète):<br>"Mon père, j'ai péché contre le ciel et contre toi. Je ne mérite plus d'être appelé ton......" <br>*26 27 28 29 30 31 32: Le père se tourne vers les domestiques et leur demande d'apporter le plus beau ........... pour l'habiller. <br>*26 27 28 29 30 31 32: Que va-t-on passer au doigt du fils? <br>*26 27 28 29 30 31 32: Pour le père, la bague, c'est un signe:<br>-->De richesse<br>-->D'alliance<br>-->De soumission<br>*26 27 28 29 30 31 32: Il est bien gras et on décide de le tuer. Qui est-ce?<br>*26 27 28 29 30 31 32 Que dit le père? Complète la phrase: "Mon fils que voilà était .........., et il est revenu à la ......</p>

<br>
<p><u>Femme adultère: </u><br>*33 34 35 36 37 38 39: Qu'amènent les scribes et les pharisiens à Jésus?<br>*33 34 35 36 37 38 39: Laquelle des deux propositions est vraie?: La femme de l'évangile n'a jamais péché. La femme de l'évangile a péché. <br>*33 34 35 36 37 38 39: Autre nom donné à Jésus dans l'évangile. Choisis parmi les propositions:  Père; maître; scribe.  <br>*33 34 35 36 37 38 39: Donne le nom du prophète du premier Testament qui a reçu les tables de la Loi.<br>*33 34 35 36 37 38 39: Que signifie le mot "Lapider"?<br>*33 34 35 36 37 38 39: La femme a commis un péché? Que veulent faire les scribes et les pharisiens?<br>*33 34 35 36 37 38 39: Que dit Jésus? "Celui d'entre vous qui est sans ............., qu'il soit le .............. à lui jeter la pierre." <br>*33 34 35 36 37 38 39: Les hommes ont écouté Jésus. Ils sont vont l'un après l'autre. Quels sont ceux qui partent en premier (les plus jeunes; les hommes d'âge moyen; les plus vieux).<br>*33 34 35 36 37 38 39: Pourquoi les hommes partent-ils les uns après les autres?<br>*33 34 35 36 37 38 39: En fin d'évangile, est-ce que les scribes et les pharisiens condamnent la femme?<br>*33 34 35 36 37 38 39: Qui condamne la femme? <br>*33 34 35 36 37 38 39: Complète la phrase dite par Jésus: " Moi non plus, je ne te condamne pas. Va et désormais, ne ............ plus." <br>*33 34 35 36 37 38 39: Cet évangile a été écrit par Jean. Donne le nom d'un autre évangéliste.</p>

<br>
<p><u>Rameaux: l'âne de Béthanie.</u><br>*40 41 42 43: Jésus envoie deux de ses disciples dans un village. Que vont-ils chercher?<br>*40 41 42 43: Si on demande aux disciples: "Pourquoi détachez-vous l'ânon?" Que devront-ils répondre?<br>*40 41 42 43: Que jettent les disciples sur le dos de l'ânon?<br>*40 41 42 43: Qui monte sur l'ânon?<br>*40 41 42 43: Sur le chemin, qu'étendent les gens?<br>*40 41 42 43: Complète la phrase: "Quand Jésus approche de Jérusalem, toute la foule des disciples se mirent à .......... Dieu." <br>*40 41 42 43: Qu'est-ce qu'un disciple?<br>*40 41 42 43: Complète la phrase: "Béni soit le roi qui vient au nom du ................!" <br>*40 41 42 43: A l'église, on lit cet évangile lors de la fête des ..............<br>*40 41 42 43: Le dimanche des rameaux, une semaine importante pour les chrétiens commence. Comment appelle-t-on cette semaine?</p>

<br>
<p><u>Jeudi saint- Vendredi saint: </u><br>*44 45 46: Jésus va prendre un dernier repas avec ses disciples. Comment s'appelle ce repas?<br>*44 45 46: Jésus va prendre un dernier repas avec ses disciples. Quel jour revivons-nous ce repas?<br>*44 45 46: Au cours de son dernier repas, Jésus prend du pain et le compare à son .......<br>*44 45 46: Au cours de son dernier repas, Jésus prend du vin et le compare à son ..........<br>*44 45 46: Pour qui est versé le sang de Jésus?<br>*44 45 46: Lors du repas, Jésus se lève, verse de l'eau dans une cuvette. Que fait-il ensuite?<br>*44 45 46: Quel disciple refuse, au départ, que Jésus lui lave les pieds?<br>*44 45 46: Dans le texte du lavement des pieds, que fait le maître? (Il commande. Il observe la scène. Il se met au service des autres en leur lavant lui-même les pieds).<br>*44 45 46: Après le repas, où vont Jésus et ses disciples?<br>*44 45 46: Que fait Jésus dans le jardin des oliviers?<br>*44 45 46: Au jardin des oliviers, que font les disciples? <br>*44 45 46: Jésus va être arrêté. Devant qui est-il conduit?<br>*44 45 46: Comment appelle-t-on la mort sur la croix?<br>*44 45 46: Un passant aide Jésus à porter sa croix. Qui est-ce?</p>

<br>
<p><u>Pâques: </u><br>*47: Qui se rend au tombeau le dimanche matin? <br>*47: Pourquoi les femmes se rendent-elles au tombeau le dimanche matin?<br>*47: Que découvrent les femmes en arrivant au tombeau le dimanche matin?<br>*47: Les femmes voient-elles le corps de Jésus dans le tombeau?<br>*47: Qui apparait aux femmes?<br>*47: Près du tombeau, que disent les hommes aux vêtements blancs aux femmes? <br>*47: Les femmes quittent le tombeau. Que font-elles ensuite?<br>*47 Est-ce que les apôtres croient les femmes?<br>*47: Que fait Pierre?</p>



<br>
<h2 class="txt-bleuFonce souligne">LA REGLE DU JEU:</h2>
<br>
<p>Un joueur lance le dé. Il fait trois par exemple. <br>Il regarde la case où il doit tomber. Dans ce cas de figure, il tombe sur la case 3. <br>Il doit répondre à une question tirée des questions 1234.<br>S'il répond bien, il peut avancer son pion jusqu'à la case 3. Sinon, il reste où il est.</p>
<br><br>